name: build

on:
  repository_dispatch:
    types: [build]

env:
  TAG: ${{ github.event.client_payload.tag }}
  REGISTRY: "ghcr.io"
  REPO: "jimboid"
  IMAGE_NAME: biosim-ubiquitin-analysis-workshop

jobs:
  base-build:
    runs-on: ubuntu-24.04
    name: workshop-build
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build . --build-arg BASE_IMAGE=${{ env.TAG }} \
          -t ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
          -t ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest

      - name: Authenticate with GHCR
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.BUILD_TOKEN}}

      - name: Push image
        run: |
          docker push --all-tags ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}

