name: Build workshop

on:
  repository_dispatch:
    types: [build]

env:
  TAG: ${{ github.event.client_payload.tag }}
  REGISTRY: "harbor.stfc.ac.uk"
  REPO: "biosimulation-cloud"
  IMAGE_NAME: biosim-ubiquitin-analysis-workshop

jobs:
  base-build:
    runs-on: ubuntu-24.04
    name: workshop-build
    steps:
      - uses: actions/checkout@v4

      - name: Build image
        run: |
          docker build . --build-arg BASE_IMAGE=${{ env.TAG }} \
          -t ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:${{ env.TAG }} \
          -t ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}:latest

      - name: Authenticate with harbor
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Push to Harbor
        run: |
          docker push --all-tags ${{ env.REGISTRY }}/${{ env.REPO }}/${{ env.IMAGE_NAME }}

